from fastapi import APIRouter, Depends, UploadFile, File, Form, BackgroundTasks, HTTPException, Response
from app.schemas.submission_schema import SubmissionResponse
from app.services.submission_service import SubmissionService
from app.database.mongodb import get_database
from app.utils.dependencies import get_current_user
import os
import io
import json
import subprocess
import urllib.request
import zipfile
import sys

router = APIRouter()

def get_submission_service(db = Depends(get_database)) -> SubmissionService:
    return SubmissionService(db)

@router.post("/", response_model=SubmissionResponse)
async def submit_job(
    target_column: str = Form(...),
    use_case: str = Form(...),
    requirement: str = Form(...),
    dataset: UploadFile = File(...),
    current_user: dict = Depends(get_current_user),
    submission_service: SubmissionService = Depends(get_submission_service)
):
    """Submits the model requirements and uploads the dataset securely."""
    user_id = str(current_user["_id"])
    return await submission_service.create_submission(
        user_id=user_id, 
        file=dataset, 
        target_column=target_column,
        use_case=use_case,
        requirement=requirement
    )

@router.get("/", response_model=list[SubmissionResponse])
async def get_my_submissions(
    current_user: dict = Depends(get_current_user),
    submission_service: SubmissionService = Depends(get_submission_service)
):
    """Retrieves all submissions for the logged-in user."""
    user_id = str(current_user["_id"])
    return await submission_service.get_user_submissions(user_id)


async def run_training_pipeline(submission_id: str, service: SubmissionService):
    try:
        # 1. Mark as training
        await service.update_submission_status(submission_id, "training")
        
        # 2. Get Submission metadata
        sub = await service.get_submission(submission_id)
        if not sub: return

        csv_url = sub["dataset_url"]
        target = sub["target_column"]
        use_case = sub["use_case"]
        requirement = sub["requirement"]
        
        # 3. Download the actual CSV to local tmp
        local_csv = f"{submission_id}.csv"
        urllib.request.urlretrieve(csv_url, local_csv)
        
        # 4. Trigger Model_Training module
        cmd = [
            sys.executable, "Model_Training/main.py",
            "--csv_path", local_csv,
            "--target", target,
            "--use_case", use_case,
            "--req", requirement
        ]
        
        process = subprocess.run(cmd, capture_output=True, text=True)
        if process.returncode != 0:
            print("Training Error:", process.stderr)
            await service.update_submission_status(submission_id, "failed")
            return
            
        # 5. Read Output Artifacts generated by the Training Module
        safe_name = target.replace(" ", "_").lower()
        model_save_path = f"{safe_name}_best_model.pth"
        config_save_path = f"{safe_name}_model_config.json"
        
        with open(model_save_path, "rb") as f:
            model_bytes = f.read()
            
        with open(config_save_path, "r") as f:
            config_dict = json.load(f)
            
        # 6. Save the binary model to the database directly
        await service.save_trained_model(submission_id, model_bytes, config_dict)
        
        # 7. Cleanup local files
        if os.path.exists(local_csv): os.remove(local_csv)
        if os.path.exists(model_save_path): os.remove(model_save_path)
        if os.path.exists(config_save_path): os.remove(config_save_path)
        
    except Exception as e:
        print("Exception in background training:", str(e))
        await service.update_submission_status(submission_id, "failed")


@router.post("/{submission_id}/train")
async def trigger_training(
    submission_id: str, 
    background_tasks: BackgroundTasks,
    current_user: dict = Depends(get_current_user),
    submission_service: SubmissionService = Depends(get_submission_service)
):
    """Triggers the background training pipeline."""
    sub = await submission_service.get_submission(submission_id)
    if not sub:
        raise HTTPException(status_code=404, detail="Submission not found")
    if str(sub["user_id"]) != str(current_user["_id"]):
        raise HTTPException(status_code=403, detail="Not authorized")
        
    background_tasks.add_task(run_training_pipeline, submission_id, submission_service)
    return {"message": "Training started"}


@router.get("/{submission_id}/download")
async def download_model(
    submission_id: str,
    current_user: dict = Depends(get_current_user),
    submission_service: SubmissionService = Depends(get_submission_service)
):
    """Downloads the trained model and config as a ZIP file."""
    sub = await submission_service.get_submission(submission_id)
    if not sub:
        raise HTTPException(status_code=404, detail="Submission not found")
    if str(sub["user_id"]) != str(current_user["_id"]):
        raise HTTPException(status_code=403, detail="Not authorized")
        
    if sub.get("status") != "completed" or not sub.get("model_artifact"):
        raise HTTPException(status_code=400, detail="Model is not ready yet.")
        
    # Create the zip in memory
    zip_buffer = io.BytesIO()
    model_bytes = sub["model_artifact"]
    config_str = json.dumps(sub["model_config_json"], indent=4)
    target = sub["target_column"]
    safe_name = target.replace(" ", "_").lower()
    
    with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
        zip_file.writestr(f"{safe_name}_best_model.pth", model_bytes)
        zip_file.writestr(f"{safe_name}_model_config.json", config_str)
        
    return Response(
        content=zip_buffer.getvalue(),
        media_type="application/zip",
        headers={"Content-Disposition": f"attachment; filename={safe_name}_model_artifacts.zip"}
    )


@router.post("/{submission_id}/predict")
async def predict_with_model(
    submission_id: str,
    test_data: UploadFile = File(...),
    current_user: dict = Depends(get_current_user),
    submission_service: SubmissionService = Depends(get_submission_service)
):
    """Feeds new sample data into the completed model and returns predictions."""
    sub = await submission_service.get_submission(submission_id)
    if not sub:
        raise HTTPException(status_code=404, detail="Submission not found")
    if str(sub["user_id"]) != str(current_user["_id"]):
        raise HTTPException(status_code=403, detail="Not authorized")
        
    if sub.get("status") != "completed" or not sub.get("model_artifact"):
        raise HTTPException(status_code=400, detail="Model is not fully trained yet.")
        
    if test_data.filename and not test_data.filename.endswith(".csv"):
        raise HTTPException(status_code=400, detail="Only CSV sample data is supported.")
        
    sample_bytes = await test_data.read()
    
    # Import locally because it depends on torch which is heavy
    from app.utils.predict_utils import run_prediction_pipeline
    
    try:
        result = run_prediction_pipeline(submission_id, sub, sample_bytes)
        return result
    except Exception as e:
        print("Error during prediction:", str(e))
        raise HTTPException(status_code=500, detail=f"Prediction failed: {str(e)}")

